# Generated by Django 3.2.5 on 2021-07-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edgeId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fnodeId', models.PositiveIntegerField()),
                ('enodeId', models.PositiveIntegerField()),
                ('korName', models.CharField(max_length=20)),
                ('roadLength', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'edge_information',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nodeType', models.PositiveSmallIntegerField()),
                ('korName', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('linkedNode', models.JSONField()),
            ],
            options={
                'db_table': 'node_information',
            },
        ),
    ]
