# Generated by Django 3.2.5 on 2021-07-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextNode',
        ),
    ]
